---
sidebar: sidebar
permalink: reference-configs-aws.html
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks, networking, bandwidth, professional package
summary: Several Cloud Volumes ONTAP configurations are supported in AWS.
---

= Supported configurations for Cloud Volumes ONTAP in AWS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Several Cloud Volumes ONTAP configurations are supported in AWS. 

== Supported disks in AWS
In addition to the storage for user data, the NetApp also purchases cloud storage for system data in AWS.

=== Internal disks for system data

The following internal disks are used for system data in AWS:

* Three disks per node for boot, root, and core data:
** 47 GiB io1 disk for boot data
** 140 GiB gp3 disk for root data
** 540 GiB gp2 disk for core data
* For HA pairs:
** Two st1 EBS volumes for the mediator instance, one of approximately 8 GiB as root disk, and one of 4 GiB as data disk
** One 140 GiB gp3 disk in each node to contain a copy of the root data of the other node
+
NOTE: In some zones, the available EBS disk type can only be gp2.
+
* One EBS snapshot for each boot disk and root disk
+
NOTE: Snapshots are created automatically upon reboot.
+
* When you enable data encryption in AWS using the Key Management Service (KMS), the boot and root disks for Cloud Volumes ONTAP are encrypted, as well. This includes the boot disk for the mediator instance in an HA pair. The disks are encrypted using the CMK that you select when you add a Cloud Volumes ONTAP system.

TIP: In AWS, NVRAM is on the boot disk.


=== AWS storage for user data

In AWS, Cloud Volumes ONTAP uses EBS storage for user data and local NVMe storage as Flash Cache on some EC2 instance types.

EBS storage::
In AWS, an aggregate can contain up to 6 disks that are all the same size. But if you have a configuration that supports the Amazon EBS Elastic Volumes feature, then an aggregate can contain up to 8 disks. link:concept-aws-elastic-volumes.html[Learn more about support for Elastic Volumes].
+
The maximum disk size is 16 TiB.
+
The underlying EBS disk type can be either General Purpose SSDs (gp3 or gp2), Provisioned IOPS SSD (io1), or Throughput Optimized HDD (st1). You can pair an EBS disk with Amazon Simple Storage Service (Amazon S3) to link:concept-data-tiering.html[low-cost object storage].
+
NOTE: Tiering data to object storage is not recommended when using Throughput Optimized HDDs (st1).

Local NVMe storage::
Some EC2 instance types include local NVMe storage, which Cloud Volumes ONTAP uses as link:concept-flash-cache.html[Flash Cache].

=== Supported disk sizes

In AWS, an aggregate can contain up to 6 disks that are all the same size. But if you have a configuration that supports the Amazon EBS Elastic Volumes feature, then an aggregate can contain up to 8 disks. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html[Learn more about support for Elastic Volumes^]

[cols=3*,options="header"]
|===

| General Purpose SSDs (gp3 and gp2)
| Provisioned IOPS SSDs (io1)
| Throughput Optimized HDDs (st1)

a|
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

a|
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

a|
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB
|===

== Supported number of nodes

Cloud Volumes ONTAP is available in AWS as a single-node system and as a high-availability (HA) pair of nodes for fault tolerance and nondisruptive operations.

Upgrading a single-node system to an HA pair is not supported. If you want to switch between a single-node system and an HA pair, then you need to deploy a new system and replicate data from the existing system to the new system.

== Supported storage

Cloud Volumes ONTAP supports several types of EBS disks, and S3 object storage for data tiering. The maximum storage capacity is determined by the license that you choose.

=== Storage support by license

Each license supports a different maximum system capacity. The maximum system capacity includes disk-based storage plus object storage used for data tiering. NetApp doesn’t support exceeding this limit.

The following tables list the supported storage and EC2 machine type combinations for each license. For the latest EC2 instance specifications, including vCPU, memory, network bandwidth, and Amazon EBS bandwidth, refer to https://aws.amazon.com/ec2/instance-types/[Amazon EC2 instance types^].

Cloud Volumes ONTAP can run on either a Reserved or On-demand EC2 instance. Solutions that use other instance types aren't supported.

[role="tabbed-block"]
====

.Capacity-based licenses
--
[cols="h,d,d",options="header"]
|===
a|
a| Freemium 
a| Capacity-based license (Essentials and Professional)

a| *Maximum system capacity* ^1^
(disks + object storage)
| 500 GiB
a| Flexible ^2^

a| *Supported machine types*
2+a|

.C5 series
[%collapsible]
======
* c5.9xlarge
* c5.18xlarge ^7^
======

.C5a series
[%collapsible]
======
* c5a.12xlarge
======

.C5d series
[%collapsible]
======
* c5d.4xlarge ^8^
* c5d.9xlarge
* c5d.18xlarge ^7^
======

.C5n series
[%collapsible]
======
* c5n.9xlarge
* c5n.18xlarge ^7^
======

.M5 series
[%collapsible]
======
* m5.xlarge ^8^
* m5.2xlarge ^8^
* m5.4xlarge ^8^
* m5.16xlarge
======

.M5a series
[%collapsible]
======
* m5a.2xlarge
* m5a.16xlarge
======

.M5d series
[%collapsible]
======
* m5d.8xlarge
* m5d.12xlarge
======

.M5dn series
[%collapsible]
======
* m5dn.4xlarge
* m5dn.12xlarge
* m5dn.24xlarge ^7^
======

.M5n series
[%collapsible]
======
* m5n.2xlarge
======

.M6id series
[%collapsible]
======
* m6id.xlarge ^9^
* m6id.2xlarge ^9^
* m6id.4xlarge ^9^
* m6id.8xlarge ^9^
* m6id.16xlarge ^7,9^
* m6id.32xlarge ^7,9^
======

.M6idn series
[%collapsible]
======
* m6idn.xlarge ^9^
* m6idn.2xlarge ^9^
* m6idn.4xlarge ^9^
* m6idn.8xlarge ^9^
* m6idn.16xlarge ^7,9^
* m6idn.32xlarge ^9^
======

.R5 series
[%collapsible]
======
* r5.xlarge ^8^
* r5.2xlarge ^8^
* r5.8xlarge
* r5.12xlarge ^6^
======

.R5d series
[%collapsible]
======
* r5d.2xlarge
======

a| *Supported disk types*
2+a|
* General Purpose SSD (gp3 and gp2) ^3^,^5^
* Provisioned IOPS SSD (io1) ^3^
* Throughput Optimized HDD (st1) ^4^

a| *Cold data tiering to S3* 2+a| Supported |
|===

. For an HA pair, the capacity limit is for the entire HA pair. It's not per node. For example, if you use the PAYGO Premium license, you can have up to 368 TiB of capacity between both nodes.
. For some configurations, disk limits prevent you from reaching the capacity limit by using disks alone. In those cases, you can reach the capacity limit by https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html[tiering inactive data to object storage^]. For information about disk limits, refer to link:reference-limits-aws.html[storage limits].
+
include::_include/capacity-limit.adoc[] 
. Enhanced write performance is enabled when using SSDs with all Cloud Volumes ONTAP configurations, except for PAYGO Explore.
. Tiering data to object storage isn't recommended when using Throughput Optimized HDDs (st1).
. Cloud Volumes ONTAP configurations in AWS Local Zones support only the General Purpose SSD (gp2) disk type. No other disk types are supported in AWS Local Zones.
. The r5.12xlarge instance type has a known limitation with supportability. If a node unexpectedly reboots due to a panic, the system might not collect core files used to troubleshoot and root cause the problem. The customer accepts the risks and limited support terms and bears all support responsibility if this condition occurs. This limitation affects newly deployed HA pairs and HA pairs upgraded from 9.8. The limitation does not affect newly deployed single-node systems.
. While these EC2 instance types support more than 64 vCPUs, Cloud Volumes ONTAP supports up to 64 vCPUs.
. AWS Local Zones are supported in the following EC2 instance type families with sizes xlarge to 4xlarge: M5, C5, C5d, R5, and R5d. link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/?nc=sn&loc=2[You should refer to AWS for the latest and complete details about supported EC2 instance types in Local Zones^].
+
High write speed isn't supported with these instance types in AWS Local Zones.
. These instance types require ONTAP 9.16.1 GA or later.

--

.Other licenses 
--
[cols="h,d,d,d,d",options="header"]
|===
|
| PAYGO Explore
| PAYGO Standard
| PAYGO Premium
| Node-based BYOL

| Maximum system capacity
(disks + object storage) | 2 TiB | 10 TiB | 368 TiB ^2^| 368 TiB per license ^2^

| Supported machine types

a|

.M5 series
[%collapsible]
======
* m5.xlarge ^8^
======

.M6id series
[%collapsible]
======
* m6id.xlarge ^9^
======

.M6idn series
[%collapsible]
======
* m6idn.xlarge ^9^
======

a|

.M5 series
[%collapsible]
======
* m5.2xlarge ^8^
======

.M5a series
[%collapsible]
======
* m5a.2xlarge
======

.M6id series
[%collapsible]
======
* m6id.2xlarge ^9^
======

.M6idn series
[%collapsible]
======
* m6idn.2xlarge ^9^
======

.R5 series
[%collapsible]
======
* r5.xlarge ^8^
======

a|

.C5 series
[%collapsible]
======
* c5.9xlarge
* c5.18xlarge ^7^
======

.C5a series
[%collapsible]
======
* c5a.12xlarge
======

.C5d series
[%collapsible]
======
* c5d.4xlarge ^8^
* c5d.9xlarge
* c5d.18xlarge ^7^
======

.C5n series
[%collapsible]
======
* c5n.9xlarge
* c5n.18xlarge ^7^
======

.M5 series
[%collapsible]
======
* m5.4xlarge ^8^
* m5.16xlarge
======

.M5a series
[%collapsible]
======
* m5a.16xlarge
======

.M5d series
[%collapsible]
======
* m5d.8xlarge
* m5d.12xlarge
======

.M5dn series
[%collapsible]
======
* m5dn.4xlarge
* m5dn.12xlarge
* m5dn.24xlarge ^7^
======

.M5n series
[%collapsible]
======
* m5n.2xlarge
======

.M6id series
[%collapsible]
======
* m6id.4xlarge ^9^
* m6id.8xlarge ^9^
* m6id.16xlarge ^7,9^
* m6id.32xlarge ^7,9^
======

.M6idn series
[%collapsible]
======
* m6idn.4xlarge ^9^
* m6idn.8xlarge ^9^
* m6idn.16xlarge ^7,9^
* m6idn.32xlarge ^9^
======

.R5 series
[%collapsible]
======
* r5.2xlarge ^8^
* r5.8xlarge
* r5.12xlarge ^6^
======

.R5d series
[%collapsible]
======
* r5d.2xlarge
======

a|

.C5 series
[%collapsible]
======
* c5.9xlarge
* c5.18xlarge ^7^
======

.C5a series
[%collapsible]
======
* c5a.12xlarge
======

.C5d series
[%collapsible]
======
* c5d.4xlarge ^8^
* c5d.9xlarge
* c5d.18xlarge ^7^
======

.C5n series
[%collapsible]
======
* c5n.9xlarge
* c5n.18xlarge ^7^
======

.M5 series
[%collapsible]
======
* m5.xlarge ^8^
* m5.2xlarge ^8^
* m5.4xlarge ^8^
* m5.16xlarge
======

.M5a series
[%collapsible]
======
* m5a.2xlarge
* m5a.16xlarge
======

.M5d series
[%collapsible]
======
* m5d.8xlarge
* m5d.12xlarge
======

.M5dn series
[%collapsible]
======
* m5dn.4xlarge
* m5dn.12xlarge
* m5dn.24xlarge ^7^
======

.M5n series
[%collapsible]
======
* m5n.2xlarge
======

.M6id series
[%collapsible]
======
* m6id.xlarge ^9^
* m6id.2xlarge ^9^
* m6id.4xlarge ^9^
* m6id.8xlarge ^9^
* m6id.16xlarge ^7,9^
* m6id.32xlarge ^7,9^
======

.M6idn series
[%collapsible]
======
* m6idn.xlarge ^9^
* m6idn.2xlarge ^9^
* m6idn.4xlarge ^9^
* m6idn.8xlarge ^9^
* m6idn.16xlarge ^7,9^
* m6idn.32xlarge ^9^
======

.R5 series
[%collapsible]
======
* r5.xlarge ^8^
* r5.2xlarge ^8^
* r5.8xlarge
* r5.12xlarge ^6^
======

.R5d series
[%collapsible]
======
* r5d.2xlarge
======

| Supported disk types 4+a|
* General Purpose SSD (gp3 and gp2) ^3^,^5^
* Provisioned IOPS SSD (io1) ^3^
* Throughput Optimized HDD (st1) ^4^

| Cold data tiering to S3 | Not supported 3+| Supported
|===

. For an HA pair, the capacity limit is for the entire HA pair. It's not per node. For example, if you use the PAYGO Premium license, you can have up to 368 TiB of capacity between both nodes.
. For some configurations, disk limits prevent you from reaching the capacity limit by using disks alone. In those cases, you can reach the capacity limit by https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html[tiering inactive data to object storage^]. For information about disk limits, refer to link:reference-limits-aws.html[storage limits].
+
include::_include/capacity-limit.adoc[]
. Enhanced write performance is enabled when using SSDs with all Cloud Volumes ONTAP configurations, except for PAYGO Explore.
. Tiering data to object storage isn't recommended when using Throughput Optimized HDDs (st1).
. Cloud Volumes ONTAP configurations in AWS Local Zones support only the General Purpose SSD (gp2) disk type. No other disk types are supported in AWS Local Zones.
. The r5.12xlarge instance type has a known limitation with supportability. If a node unexpectedly reboots due to a panic, the system might not collect core files used to troubleshoot and root cause the problem. The customer accepts the risks and limited support terms and bears all support responsibility if this condition occurs. This limitation affects newly deployed HA pairs and HA pairs upgraded from 9.8. The limitation does not affect newly deployed single-node systems.
. While these EC2 instance types support more than 64 vCPUs, Cloud Volumes ONTAP supports up to 64 vCPUs.
. AWS Local Zones are supported in the following EC2 instance type families with sizes xlarge to 4xlarge: M5, C5, C5d, R5, and R5d. link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/?nc=sn&loc=2[You should refer to AWS for the latest and complete details about supported EC2 instance types in Local Zones^].
+
High write speed isn't supported with these instance types in AWS Local Zones.
. These instance types require ONTAP 9.16.1 GA or later.

--
====

=== c4, m4, and r4 instances no longer supported

Cloud Volumes ONTAP no longer supports the c4, m4, and r4 EC2 instance types in AWS.

If your system runs on a c4, m4, or r4 instance, change it to a c5, m5, or r5 instance before you upgrade to this release.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html[Learn how to change the EC2 instance type for Cloud Volumes ONTAP^].

For more information, refer to the following resources:

* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Converting_an_AWS_Xen_CVO_instance_to_Nitro_KVM[Knowledge base (KB) article: Converting an AWS Xen CVO instance to Nitro KVM^]
* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Unable_to_change_the_instance_type_from_r4_to_r5_with_disk_count_error[KB article: Unable to change the instance type from r4 to r5 with disk count error^]
* link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html[Learn more about the end of availability and support for these instance types^]


== Support for Flash Cache and high write speed

The following table identifies which supported EC2 instance types support Flash Cache and high write speed. 

[cols="d,d,d",options="header"]
|===
| Supported instance
| Flash Cache
| High write speed

| c5.9xlarge
| Not supported
| Supported

| c5.18xlarge
| Not supported
| Supported

| c5a.12xlarge
| Not supported
| Supported

| c5d.4xlarge
| Supported
| Supported

| c5d.9xlarge
| Supported
| Supported

| c5d.18xlarge
| Supported
| Supported

| c5n.9xlarge
| Not supported
| Supported

| c5n.18xlarge
| Not supported
| Supported

| m5.xlarge
| Not supported
| Supported (single node only)

| m5.2xlarge
| Not supported
| Supported

| m5.4xlarge
| Not supported
| Supported

| m5.16xlarge
| Not supported
| Supported

| m5a.2xlarge
| Not supported
| Supported

| m5a.16xlarge
| Not supported
| Supported

| m5d.8xlarge
| Supported
| Supported

| m5d.12xlarge
| Supported
| Supported

| m5dn.4xlarge
| Supported
| Supported

| m5dn.12xlarge
| Supported
| Supported

| m5dn.24xlarge
| Supported
| Supported

| m5n.2xlarge
| Not supported
| Supported

| m6id.xlarge
| Supported ^*^
| Supported (single node only)

| m6id.2xlarge
| Supported ^*^
| Supported

| m6id.4xlarge
| Supported
| Supported

| m6id.8xlarge
| Supported
| Supported

| m6id.16xlarge
| Supported
| Supported

| m6id.32xlarge
| Supported
| Supported

| m6idn.xlarge
| Supported ^*^
| Supported (single node only)

| m6idn.2xlarge
| Supported ^*^
| Supported

| m6idn.4xlarge
| Supported
| Supported

| m6idn.8xlarge
| Supported
| Supported

| m6idn.16xlarge
| Supported
| Supported

| m6idn.32xlarge
| Supported
| Supported

| r5.xlarge
| Not supported
| Supported (single node only)

| r5.2xlarge
| Not supported
| Supported

| r5.8xlarge
| Not supported
| Supported

| r5.12xlarge
| Not supported
| Supported

| r5d.2xlarge
| Supported
| Supported
|===

pass:[*] Flash Cache is supported on m6id.xlarge, m6id.2xlarge, m6idn.xlarge, and m6idn.2xlarge. However, these instance types have fewer than 16 core processors and are not recommended for high-performance or memory-intensive workloads. Under heavy load, they may restart due to memory constraints. To avoid this, use an instance type with a higher core count and larger memory.

The following notes provide general guidance about supported instance behavior and deployment options.

* Some instance types include local NVMe storage, which Cloud Volumes ONTAP uses as Flash Cache. Flash Cache speeds access to data through real-time intelligent caching of recently read user data and NetApp metadata. It's effective for random read-intensive workloads, including databases, email, and file services. Compression must be disabled on all volumes to take advantage of the Flash Cache performance improvements. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html[Learn more about Flash Cache^].

* Cloud Volumes ONTAP supports high write speed with all supported instance types when using a single-node system. When using an HA pair, high write speed is supported only with supported instance types. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html[Learn more about choosing a write speed^].

* When you choose an EC2 instance type, you can specify whether it is a shared instance or a dedicated instance.



=== Supported regions

For AWS region support, see https://bluexp.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].

//BLUEXPDOC-129, BLUEXPDOC-133

.Related information

* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html[Amazon EC2 instance types^]
* https://aws.amazon.com/ec2/instance-types/m5/[Amazon EC2 M5 instances^]
* https://aws.amazon.com/ec2/instance-types/m6i/[Amazon EC2 M6i instances^]
* https://aws.amazon.com/ec2/instance-types/c5/[Amazon EC2 C5 instances^]
* https://aws.amazon.com/ec2/instance-types/r5/[Amazon EC2 R5 instances^]

//BLUEXPDOC-129, BLUEXPDOC-133