---
sidebar: sidebar
permalink: reference-limitations.html
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr, BlueXP, Console, cloud manager
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---

= Known limitations
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

These limitations are specific to Cloud Volumes ONTAP management in the NetApp Console. To view limitations with the Cloud Volumes ONTAP software itself, https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html[go to the Cloud Volumes ONTAP Release Notes^].

== Console doesn't support FlexGroup volumes creation

While Cloud Volumes ONTAP supports FlexGroup volumes, the Console does not currently support FlexGroup volume creation. If you create a FlexGroup volume from ONTAP System Manager or the ONTAP CLI, then you should set the Capacity Management mode in the Console to `Manual`. `Automatic` mode might not work properly with FlexGroup volumes.

NOTE: The ability to create FlexGroup volumes in the Console is planned for a future release. 

== Console doesn't support S3 with Cloud Volumes ONTAP

While Cloud Volumes ONTAP supports S3 as an option for scale-out storage, the Console doesn't provide any management capabilities for this feature. Using the CLI is the best practice to configure S3 client access from Cloud Volumes ONTAP. For details, refer to the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html[ONTAP S3 Configuration Power Guide^].

link:concept-client-protocols.html[Learn more about Cloud Volumes ONTAP support for ONTAP S3 and other client protocols].

== Console doesn't support disaster recovery for storage VMs

The Console doesn't provide any setup or orchestration support for storage VM (SVM) disaster recovery. You must use ONTAP System Manager or the ONTAP CLI.

link:task-manage-svm-dr.html[Learn more about SVM disaster recovery].