---
sidebar: sidebar
permalink: reference-versions.html
keywords: versions, supported versions, new versions, cloud volumes ontap version
summary: NetApp Console enables you to choose from several different ONTAP versions when you create a new Cloud Volumes ONTAP system.
---

= Supported ONTAP versions for Cloud Volumes ONTAP deployments
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The NetApp Console enables you to choose from several different ONTAP versions when you add a Cloud Volumes ONTAP system.

Cloud Volumes ONTAP versions other than those listed here are not available for new deployments. The patch or the generic (General Availability) version in a release here represents the base version available for deployment. For details about the available patches, refer to the https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-new.html[versioned release notes^] for each release.

For information on upgrade, refer to link:task-updating-ontap-cloud.html#supported-upgrade-paths[Supported upgrade paths].

ifdef::aws[]
== AWS

Single node::

* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9.8
* 9.7 P5
* 9.5 P6

HA pair::

* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9.8
* 9.7 P5
* 9.5 P6
endif::aws[]

ifdef::azure[]
== Azure

Single node::

* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18

HA pair::

* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18

endif::azure[]

ifdef::gcp[]
== Google Cloud

Single node::

* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9.8
* 9.7 P5

HA pair::

* 9.17.1 P1   
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9.8
endif::gcp[]
