---
sidebar: sidebar
permalink: task-verify-autosupport.html
keywords: autosupport, set up autosupport, test autosupport, asup, test asup
summary: AutoSupport proactively monitors the health of your system and sends messages to NetApp technical support. By default, AutoSupport is enabled on each node to send messages to technical support using the HTTPS transport protocol. It's best to verify that AutoSupport can send these messages.
---

= Verify AutoSupport setup for Cloud Volumes ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
AutoSupport proactively monitors the health of your system and sends messages to NetApp technical support. By default, AutoSupport is enabled on each node to send messages to technical support using the HTTPS transport protocol. It's best to verify that AutoSupport can send these messages.

The only required configuration step is to ensure that Cloud Volumes ONTAP has outbound internet connectivity. For details, refer to the networking requirements for your cloud provider.

== AutoSupport requirements

Cloud Volumes ONTAP nodes require outbound internet access for NetApp AutoSupport, which proactively monitors the health of your system and sends messages to NetApp technical support.

Routing and firewall policies must allow HTTPS traffic to the following endpoints so Cloud Volumes ONTAP can send AutoSupport messages:

* \https://mysupport.netapp.com/aods/asupmessage
* \https://mysupport.netapp.com/asupprod/post/1.0/postAsup

If an outbound internet connection isn't available to send AutoSupport messages, the NetApp Console automatically configures your Cloud Volumes ONTAP systems to use the Console agent as a proxy server. The only requirement is to ensure that the Console agent's security group allows _inbound_ connections over port 3128. You'll need to open this port after you deploy the Console agent.

If you defined strict outbound rules for Cloud Volumes ONTAP, then you'll also need to ensure that the Cloud Volumes ONTAP security group allows _outbound_ connections over port 3128.

TIP: If you're using an HA pair, the HA mediator doesn't require outbound internet access.

After you've verified that outbound internet access is available, you can test AutoSupport to ensure that it can send messages. For instructions, refer to the https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html[ONTAP documentation: Set up AutoSupport^].

== Troubleshoot your AutoSupport configuration

If an outbound connection isn't available and the Console can't configure your Cloud Volumes ONTAP system to use the Console agent as a proxy server, you'll receive a notification from the Console titled "<system name> is unable to send AutoSupport messages."

You're most likely receiving this message because of networking issues.

Follow these steps to address this problem.

.Steps

. SSH to the Cloud Volumes ONTAP system so that you can administer the system from the ONTAP CLI.
+
link:task-connecting-to-otc.html[Learn how to SSH to Cloud Volumes ONTAP].

. Display the detailed status of the AutoSupport subsystem:
+
`autosupport check show-details`
+
The response looks like this:
+
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
If the status of the http-https category is "ok" then it means AutoSupport is configured properly and messages can be sent.

. If the status is not ok, verify the proxy URL for each Cloud Volumes ONTAP node:
+
`autosupport show -fields proxy-url`
+
. If the proxy URL parameter is empty, configure Cloud Volumes ONTAP to use the Console agent as a proxy:
+
`autosupport modify -proxy-url \http://<console agent private ip>:3128`
+
. Verify AutoSupport status again:
+
`autosupport check show-details`

. If the status is still is failed, validate that there is connectivity between Cloud Volumes ONTAP and the Console agent over port 3128.

. If the status ID is still failed after verifying that there is connectivity, SSH to the Console agent.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-maintain-connectors.html#connect-to-the-linux-vm[Learn more about Connecting to the Linux VM for the Console agent^]

. Go to `/opt/application/netapp/cloudmanager/docker_occm/data/`.
. Open the proxy configuration file `squid.conf`. This is the structure of the file:
+
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        http_access allow netapp_support
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on
----
+
. If your file doesn't have an entry for the CIDR block of the Cloud Volumes ONTAP system, add a new entry and allow access:
+
`acl cvonet src <cidr>`
+
`http_access allow cvonet`
+
Here's an example:
+
----
        http_port 3128
        acl netapp_support dst support.netapp.com
        acl cvonet src <cidr>
        http_access allow netapp_support
        http_access allow cvonet
        request_header_max_size 21 KB
        reply_header_max_size 21 KB
        http_access deny all
        httpd_suppress_version_string on

----

. After editing the config file, restart the proxy container as `sudo`. Then, depending on whether you're using Docker or Podman, run these commands:
+
For Docker, run `docker restart squid`.
+
If you are using Podman, run `podman restart squid`.
+
. Go back to the Cloud Volumes ONTAP CLI and verify that Cloud Volumes ONTAP can send AutoSupport messages:
+
`autosupport check show-details`


.Related links

* link:reference-networking-aws.html[Networking requirements for Cloud Volumes ONTAP in AWS^]
* link:reference-networking-azure.html[Networking requirements for Cloud Volumes ONTAP in Azure^]
* link:reference-networking-gcp.html[Networking requirements for Cloud Volumes ONTAP in Google Cloud^]
