---
sidebar: sidebar
permalink: task-azure-high-availability-mode.html
keywords: high availability mode, EnableHighAvailabilityMode, action required, nfsv4
summary: Microsoft Azure's high-availability mode should be enabled to reduce unplanned failover times and to enable NFSv4 support for Cloud Volumes ONTAP.
---

= Enable high-availability mode for Cloud Volumes ONTAP in Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Microsoft Azure's high-availability (HA) mode should be enabled to reduce unplanned failover times and to enable NFSv4 support for Cloud Volumes ONTAP. In this mode, your Cloud Volumes ONTAP HA nodes can achieve a low (60 seconds) recovery time objective (RTO) during unplanned failovers on CIFS and NFSv4 clients.


Beginning with Cloud Volumes ONTAP 9.10.1, we reduced the unplanned failover time for Cloud Volumes ONTAP HA pairs running in Microsoft Azure and added support for NFSv4. To make these enhancements available to Cloud Volumes ONTAP, you need to enable the high-availability feature on your Azure subscription.

.About this task

NetApp Console prompts you with these details when the feature needs to be enabled on an Azure subscription. 

Note the following:

*	There are no problems with the high availability of your Cloud Volumes ONTAP HA pair. This Azure feature works in concert with ONTAP to reduce the client observed application outage time for NFS protocols that result from unplanned failover events.
*	Enabling this feature is non-disruptive to Cloud Volumes ONTAP HA pairs.
*	Enabling this feature on your Azure subscription doesn't cause issues to other VMs.
* Cloud Volumes ONTAP uses an internal Azure Load Balancer during failovers of cluster and SVM management LIFs on CIFS and NFS clients. 
* When the HA mode is enabled, the Console scans the system every 12 hours to update the internal Azure Load Balancer rules.

An Azure user who has "Owner" privileges can enable the feature from the Azure CLI.

== Enable the high-availability mode in Cloud Volumes ONTAP 9.18.1 and later

.Steps

. https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart[Access the Azure Cloud Shell from the Azure Portal^]

== Enable the high-availability mode in Cloud Volumes ONTAP 9.10.1  to 9.17.1
##These steps apply to all Cloud Volumes ONTAP versions starting with 9.10.1  to 9.17.1. You only need to enable the high-availability mode once per Azure subscription. After you enable the feature, the Console automatically detects that the feature is enabled and configures the internal Azure Load Balancer for your Cloud Volumes ONTAP HA pairs.##

.Steps

. https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart[Access the Azure Cloud Shell from the Azure Portal^]

. Register the high-availability mode feature:
+
[source,azurecli]
az account set -s AZURE_SUBSCRIPTION_NAME_OR_ID
az feature register --name EnableHighAvailabilityMode --namespace Microsoft.Network
az provider register -n Microsoft.Network

. Optionally verify that the feature is now registered:
+
[source,azurecli]
az feature show --name EnableHighAvailabilityMode --namespace Microsoft.Network
+
The Azure CLI should return a result similar to the following:
+
----
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Features/providers/Microsoft.Network/features/EnableHighAvailabilityMode",
  "name": "Microsoft.Network/EnableHighAvailabilityMode",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
----
//BLUEXPDOC-207
//This topic is linked to the UI.