---
sidebar: sidebar
permalink: task-getting-started-gcp.html
keywords: google cloud platform, gcp, cloud manager, deploy the Console, launch the Console, create the Console, getting started, networking, gcp networking, service account, tiering, data tiering, bucket, fabricpool, cloud backup, storage access key, gcp role, role, iam role, permissions, gcp permissions, cloud backup, the Console
summary: Get started with Cloud Volumes ONTAP for Google Cloud in a few steps.
---

= Deployment overview for Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
For deploying Cloud Volumes ONTAP, you first need to know about your Google Cloud subscription and Cloud Volumes ONTAP licenses. You must also verify that you that you have a NetApp Console agent created for your Google Cloud project and organization. Much of the information in this topic needs to be performed as part of your Console setup before you begin to even deploy Cloud Volumes ONTAP. 

[cols="20,35,25,25",options="header"]
|===
a| Task
a| Description
a| Reference
a| Notes for private mode deployments

a| Create a Console agent
a| If you don't have a Console agent yet, create one before deploying Cloud Volumes ONTAP. If deploying in a subnet with no internet access, manually install the Console agent and access the NetApp Console running on that agent.
a| Refer to the Console setup guide:
https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-google-gcloud.html[Create a Console agent in Google Cloud^]
a| If deploying in a subnet with no internet access, manually install the Console agent on the host. Then access the NetApp Console running on that agent on that host to deploy Cloud Volumes ONTAP. Refer to the Console setup guide:
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html[Manually install the Console agent without internet access^]

a| Plan your configuration
a| The Console offers preconfigured packages that match your workload requirements, or you can create your own configuration. If you choose your own configuration, you should understand the options available to you.
a|link:task-planning-your-config-gcp.html[Plan your configuration]
a| You need to have similar planning considerations for private mode deployments.

a| Set up your networking
a|.  Ensure that your VPC and subnets will support connectivity between the Console agent and Cloud Volumes ONTAP.
. If you plan to enable data tiering, configure the Cloud Volumes ONTAP subnet for Private Google Access.
. If you're deploying an HA pair, ensure that you have four VPCs, each with their own subnet.
. If you're using a shared VPC, provide the _Compute Network User_ role to the Console agent service account.
. Enable outbound internet access from the target VPC for NetApp AutoSupport.
a| Refer to: 

* link:reference-networking-gcp.html[Networking requirements for Google Cloud] 
* Refer to the Google Cloud documentation: https://cloud.google.com/vpc/docs/configure-private-google-access[Configure Private Google Access^]
a| Outbound internet access for AutoSupport is not required. All other networking requirements remain the same.

a| Set up a service account
a| Cloud Volumes ONTAP requires a Google Cloud service account for enabling data tiering to tier cold data to low-cost object storage in Google Cloud, and also to enable NetApp Backup and recovery to back up volumes to low-cost object storage.
a| * link:task-creating-gcp-service-account.html[Set up a service account]
* link:concept-data-tiering.html[Learn about data tiering]
* Refer to the https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html[NetApp Backup and Recovery documents^]
a| No additional considerations for private mode deployments.

a| Enable Google Cloud APIs
a| Enable the required Google Cloud APIs in your project. You might have already enabled these as part of creating the Console agent.
a| Refer to the Google Cloud documentation:
https://cloud.google.com/apis/docs/getting-started#enabling_apis[Enable Google Cloud APIs^]
a| APIs must be enabled. Work with your cloud administrator to enable the required APIs in your private environment.

a| Deploy Cloud Volumes ONTAP from the Console
a| When you have performed all prerequisites, you can complete the steps in the wizard to deploy Cloud Volumes ONTAP in Google Cloud.
a| Refer to: 

* link:task-quick-deploy-gcp.html[Deploy Cloud Volumes ONTAP with Quick create]
* link:task-deploying-gcp.html[Deploy Cloud Volumes ONTAP using advanced options] 
a| Before beginning the deployment, ensure that you have purchased a node-based Cloud Volumes ONTAP license. Private mode licenses are unavailable for purchase on cloud marketplaces, and you must obtain the license file from NetApp. You should also download the file on the local host before uploading it. Refer to:

* link:concept-license-management.html[License management for node-based BYOL]
* link:task-manage-node-licenses.html[Manage node-based BYOL licenses]
* link:task-quick-deploy-gcp.html[Deploy Cloud Volumes ONTAP with Quick create]
* link:task-deploying-gcp.html[Deploy Cloud Volumes ONTAP using advanced options] 

|===

.Related links

* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html[Creating a Console agent^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html[Installing the Console agent software on a Linux host^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html[Google Cloud permissions for the Console agent^]

