---
sidebar: sidebar
permalink: task-getting-started-aws.html
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create, console
summary: Verify that you have completed the prerequisites for deploying Cloud Volumes ONTAP in AWS.
---

= Deployment overview for Cloud Volumes ONTAP in AWS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
For deploying Cloud Volumes ONTAP, you first need to know about your AWS subscription and Cloud Volumes ONTAP licenses. You must also verify that you have a NetApp Console agent created for your AWS account. Much of the information in this topic needs to be performed as part of your Console setup before you begin to even deploy Cloud Volumes ONTAP.

[cols="20,35,25,25",options="header"]
|===
a| Task
a| Description
a| Reference
a| Notes for private mode deployments

a| Create a Console agent
a| If you don't have a Console agent yet, create one before deploying Cloud Volumes ONTAP. If deploying in a subnet with no internet access, manually install the Console agent and access the NetApp Console running on that agent.
a| Refer to the Console setup guide:
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html[Create a Console agent in AWS^]

a| If deploying in a subnet with no internet access, manually install the Console agent on the host. Then access the NetApp Console running on that agent on that host to deploy Cloud Volumes ONTAP. Refer to the Console setup guide:
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html[Manually install the Console agent without internet access^]

a| Plan your configuration
a| The Console offers preconfigured packages that match your workload requirements, or you can create your own configuration. If you choose your own configuration, you should understand the options available to you.
a| link:task-planning-your-config.html[Plan your configuration]
a| You need to have similar planning considerations for private mode deployments.

a| Set up your networking
a| . Ensure your VPC and subnets support connectivity between the Console agent and Cloud Volumes ONTAP. 
. Enable outbound internet access for AutoSupport.
. Set up a VPC endpoint to Amazon S3 for data tiering. A VPC endpoint is required if you want to tier cold data from Cloud Volumes ONTAP to low-cost object storage.
a| link:reference-networking-aws.html[Networking requirements for AWS]
a| Outbound internet access for AutoSupport is not required. All other networking requirements remain the same.

a| Set up the AWS KMS
a| If you want to use Amazon encryption with Cloud Volumes ONTAP, ensure that an active Customer Master Key (CMK) exists and modify the key policy to add the IAM role for the Console agent as a key user.
a| link:task-setting-up-kms.html[Set up the AWS KMS]
a| Similar steps apply to private mode deployments.

a| Deploy Cloud Volumes ONTAP from the Console
a| When you have performed all prerequisites, you can complete the steps in the wizard to deploy Cloud Volumes ONTAP in AWS.
a| 
* link:task-quick-deploy-aws.html[Deploy Cloud Volumes ONTAP with Quick create]
* link:task-deploying-otc-aws.html[Deploy Cloud Volumes ONTAP using advanced options] 
a| Before beginning the deployment, ensure that you have purchased a node-based Cloud Volumes ONTAP license. Private mode licenses are unavailable for purchase on cloud marketplaces, and you must obtain the license file from NetApp. You should also download the file on the local host before uploading it. Refer to:

* link:concept-license-management.html[License management for node-based BYOL]
* link:task-manage-node-licenses.html[Manage node-based BYOL licenses]
* link:task-quick-deploy-aws.html[Deploy Cloud Volumes ONTAP with Quick create]
* link:task-deploying-otc-aws.html[Deploy Cloud Volumes ONTAP using advanced options] 

|===

.Related links

* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html[Create a Console agent for AWS^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html[Create a Console agent from the AWS Marketplace^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html[Install and set up a Console agent on premises^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html[AWS permissions for the Console agent^]
