---
sidebar: sidebar
permalink: task-sync-time.html
keywords: set up, setting up, ntp, time, synch
summary: Specifying an NTP server synchronizes the time between the systems in your network, which can help prevent issues due to time differences.
---

= Synchronize Cloud Volumes ONTAP system time using NTP servers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Configuring Network Time Protocol (NTP) servers for your Cloud Volumes ONTAP clusters ensures accurate time synchronization of your cluster time with other systems in your network and external servers. Syncing your cluster time with external NTP servers helps maintain consistency across your infrastructure. NetApp configures NTP servers by default for new Cloud Volumes ONTAP deployments. However, if they are not configured for your existing Cloud Volumes ONTAP clusters, you must configure NTP servers for accurate time synchronization within and outside of your network.

You can specify an NTP server using:

* https://docs.netapp.com/us-en/bluexp-automation/cm/api_ref_resources.html[The NetApp Console API^].
* The ONTAP CLI command https://docs.netapp.com/us-en/ontap-cli//cluster-time-service-ntp-server-create.html[cluster time-service ntp server create^].

[NOTE]
If you don't configure an NTP server, you might experience service disruptions and inaccurate time synchronization.


.Related links

* Knowledge base (KB) article: https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs/How_does_a_CVO_cluster_use_NTP[How does a CVO cluster use NTP?]
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html[Prepare to use the API^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows[Cloud Volumes ONTAP workflows^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier[Get required identifiers^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html[Use the REST APIs for NetApp Console^]
