---
sidebar: sidebar
permalink: task-getting-started-azure.html
keywords: microsoft, azure, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, marketplace, virtual machine, vnet, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, permissions, custom role, role, json, permissions, virtual machine, connectivity, internet, outbound, endpoint, connection, networks, vpn, replicating, policy, iam, setupasservice, sign up, cloud manager, BlueXP, cloud volumes ontap, cloud ontap, subscription, create
summary: Get started with Cloud Volumes ONTAP for Azure in a few steps.
---

= Deployment overview for Cloud Volumes ONTAP in Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
For deploying Cloud Volumes ONTAP, you first need to know about your Azure subscription and Cloud Volumes ONTAP licenses. You must also verify that you have a NetApp Console agent created for your Azure subscription and organization. Much of the information in this topic needs to be performed as part of your Console setup before you begin to even deploy Cloud Volumes ONTAP.

[cols="20,35,25,25",options="header"]
|===
a| Task
a| Description
a| Reference
a| Notes for private mode deployments

a| Create a Console agent
a| If you don't have a Console agent yet, create one before deploying Cloud Volumes ONTAP. 
a| Refer to the Console setup guide:
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html[Create a Console agent in Azure^]

a| If deploying in a subnet with no internet access, manually install the Console agent on the host. Then access the NetApp Console running on that agent on that host to deploy Cloud Volumes ONTAP. Refer to the Console setup guide:
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html[Manually install the Console agent without internet access^]

a| Plan your configuration
a| The Console offers preconfigured packages that match your workload requirements, or you can create your own configuration. If you choose your own configuration, you should understand the options available to you.
a| link:task-planning-your-config-azure.html[Plan your Cloud Volumes ONTAP configuration in Azure]
a| You need to have similar planning considerations for private mode deployments.

a| Set up your networking
a| . Ensure your VNet and subnets support connectivity between the Console agent and Cloud Volumes ONTAP. 
. Enable outbound internet access from the target VNet for NetApp AutoSupport.
a| link:reference-networking-azure.html[Networking requirements for Azure]
a| Outbound internet access for AutoSupport is not required. All other networking requirements remain the same.

a| Deploy Cloud Volumes ONTAP from the Console
a| When you have performed all prerequisites, you can complete the steps in the wizard to deploy Cloud Volumes ONTAP in Azure.
a| Refer to: 

* link:task-quick-deploy-azure.html[Deploy Cloud Volumes ONTAP with Quick create]
* link:task-deploying-otc-azure.html[Deploy Cloud Volumes ONTAP using advanced options] 
a| Before beginning the deployment, ensure that you have purchased a Cloud Volumes ONTAP license from NetApp. Private mode deployments require a node-based BYOL licenses. Marketplace subscriptions are not supported for charging your Cloud Volumes ONTAP usage. Obtain the license file from NetApp, save it to the local host, and upload it during deployment. Refer to:

* link:concept-license-management.html[License management for node-based BYOL]
* link:task-manage-node-licenses.html[Manage node-based BYOL licenses]
* link:task-quick-deploy-azure.html[Deploy Cloud Volumes ONTAP with Quick create]
* link:task-deploying-otc-azure.html[Deploy Cloud Volumes ONTAP using advanced options] 

|===

.Related links

* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html[Creating a Console agent from the Console^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-marketplace.html[Creating a Console agent from the Azure Marketplace^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html[Installing the Console agent software on a Linux host^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html[What the Console does with permissions^]
