---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, cloud manager, BlueXP, digital wallet, cloud backup, cloud data sense, cloud tiering, keystone flex, keystone
summary: Learn what's new with Cloud Volumes ONTAP management in BlueXP.
---
= What's new in Cloud Volumes ONTAP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new with Cloud Volumes ONTAP management in the NetApp Console.

The enhancements described on this page are specific to managing Cloud Volumes ONTAP through the Console. To learn what's new with the Cloud Volumes ONTAP software itself, https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html[go to the Cloud Volumes ONTAP Release Notes^].

//The whats-new tag should be enclosed around the three most recent releases. Be sure to use absolute URLs for links and images. Begin images like this: image:https://raw.githubusercontent.com/NetAppDocs/bluexp-cloud-volumes-ontap/main/media/[file-name].png. This Cis required so that the what's new content can be reused in the bluexp-relnotes doc site. To begin the tag, use //tag::whats-new[]. To end the tag, use //end::whats-new[].
//Major ONTAP releases should be included as an entry. The RN link for the last release will need to point to the downlevel entry.

== 11 June 2026
include::_whatsnew/2026-06-11.adoc[]

== 08 June 2026
include::_whatsnew/2026-06-08.adoc[]

== 18 May 2026
include::_whatsnew/2026-05-18.adoc[]

== 12 May 2026 
include::_whatsnew/2026-05-12.adoc[]

== 13 April 2026
include::_whatsnew/2026-04-13.adoc[]

== 10 March 2026
include::_whatsnew/2026-03-10.adoc[]

== 26 February 2026
include::_whatsnew/2026-02-26.adoc[]

== 19 February 2026
include::_whatsnew/2026-02-19.adoc[]

== 17 February 2026
include::_whatsnew/2026-02-17.adoc[]

== 12 February 2026
include::_whatsnew/2026-02-12.adoc[]

== 10 February 2026
include::_whatsnew/2026-02-10-918.adoc[]

== 9 February 2026
include::_whatsnew/2026-02-09.adoc[]

== 12 January 2026
include::_whatsnew/2026-01-12.adoc[]

== 10 December 2025
include::_whatsnew/2025-12-08.adoc[]

== 10 November 2025
include::_whatsnew/2025-11-10.adoc[]

== 17 October 2025
include::_whatsnew/2025-10-17.adoc[]

== 06 October 2025
include::_whatsnew/2025-10-06.adoc[]

== 04 September 2025
include::_whatsnew/2025-09-04-917.adoc[]

== 11 August 2025
include::_whatsnew/2025-08-11.adoc[]

== 14 July 2025
include::_whatsnew/2025-07-14.adoc[]

== 25 June 2025
include::_whatsnew/2025-06-25.adoc[]

== 29 May 2025
include::_whatsnew/2025-05-29.adoc[]

== 12 May 2025
include::_whatsnew/2025-05-12.adoc[]

== 16 April 2025
include::_whatsnew/2025-04-16.adoc[]

== 14 April 2025
include::_whatsnew/2025-04-14.adoc[]

== 03 April 2025
include::_whatsnew/2025-04-03.adoc[]

== 28 March 2025
include::_whatsnew/2025-03-28.adoc[]

== 12 March 2025
include::_whatsnew/2025-03-12.adoc[]

== 10 March 2025
include::_whatsnew/2025-03-10.adoc[]

== 06 March 2025
include::_whatsnew/2025-03-06-916.adoc[]


== 03 March 2025
include::_whatsnew/2025-03-03.adoc[]

== 18 February 2025
include::_whatsnew/2025-02-18.adoc[]

== 10 February 2025
include::_whatsnew/2025-02-10.adoc[]

== 09 December 2024
include::_whatsnew/2024-12-09.adoc[]

== 11 November 2024
include::_whatsnew/2024-11-11.adoc[]

== 25 October 2024
include::_whatsnew/2024-10-25.adoc[]

== 07 October 2024
include::_whatsnew/2024-10-07.adoc[]

== 09 September 2024
include::_whatsnew/2024-09-09.adoc[]


== 23 August 2024
=== Canada West region now supported in AWS
The Canada West region is now supported in AWS for Cloud Volumes ONTAP 9.12.1 GA and later.

For a list of all regions, see the https://bluexp.netapp.com/cloud-volumes-global-regions[Global Regions Map under AWS^].

== 22 August 2024

=== Cloud Volumes ONTAP 9.15.1 GA
BlueXP can now deploy and manage Cloud Volumes ONTAP 9.15.1 General Availability release in AWS, Azure, and Google Cloud.

https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/[Learn about the new features included in this release of Cloud Volumes ONTAP^].

=== Support for Premium SSD v2 Managed Disks in Azure
Premium SSD v2 Managed Disks are now supported in Cloud Volumes ONTAP systems on Azure. These premium disks provide higher performance with lower latency at a lower cost for both single node and high-availability (HA) pairs, as compared to Premium SSD Managed Disks. Like other managed disks, the maximum disk size is 32 TiB. The performance (capacity, throughput, and IOPS) of a Premium SSD v2 Managed Disks can be configured, allowing workloads to be cost effective, while meeting shifting performance needs.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage.html#azure-storage[Learn about Azure storage^].


=== Deploy HA pairs in single availability zones in Azure
Beginning with Cloud Volumes ONTAP 9.15.1, you can deploy virtual machine (VM) instances in HA mode in single availability zones (AZs) in Azure. Unlike the previous non-zonal deployments, Cloud Volumes ONTAP 9.15.1 uses Microsoft Virtual Machines Scale Sets in Flexible orchestration mode to deploy all resources, including separate fault domains within the same AZ, guaranteeing optimal availability. This deployment mode, by default, uses Premium SSD v2 Managed Disks when the following conditions are met:

* The version of Cloud Volumes ONTAP is 9.15.1 or later.
* The selected region and zone support Premium SSD v2 Managed Disks. For information about the supported regions, refer to  https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/[Microsoft Azure website: Products available by region^]. To know how to add them, refer to https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-otc-azure.html#launching-a-cloud-volumes-ontap-ha-pair-in-azure[Launching a Cloud Volumes ONTAP HA pair in Azure^].
* The subscription is registered for the Microsoft `Microsoft.Compute/VMOrchestratorZonalMultiFD` feature. 
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-saz-feature.html[Learn how to enable VMOrchestratorZonalMultiFD for single availability zones^].

If any of these criteria is not fulfilled, the previous non-zonal deployment mode for locally-redundant storage (LRS) becomes effective.

=== Support for Virtual Machines Scale Sets to unify all Azure HA types
Cloud Volumes ONTAP 9.15.1 leverages Virtual Machines Scale Sets in Flexible orchestration mode on Azure for deploying virtual machine (VM) instances in single availability zones for high-availability (HA) pairs. It covers all flavors of the HA mode, page blob, LRS, zone-redundant storage (ZRS) or multi-zonal, and LRS zonal (single AZ). 

* https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/[Microsoft Azure documentation: Virtual Machine Scale Sets documentation^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html[Learn about high-availability pairs in Azure^].

=== Support for FlexCache write-back
Beginning with Cloud Volumes ONTAP 9.15.1, FlexCache write-back is supported as an alternate mode of operation for writing at a cache. 

For more information about this feature, refer to the ONTAP documentation https://docs.netapp.com/us-en/ontap/flexcache-writeback/flexcache-write-back-overview.html[FlexCache write-back overview^].

For information about how BlueXP manages FlexCache volumes, refer to the https://docs.netapp.com/us-en/bluexp-volume-caching/index.html[BlueXP volume caching documents^].


== 08 August 2024

=== Edge Cache licensing packages deprecated
Edge Cache capacity-based licensing packages will no longer be available for future deployments of Cloud Volumes ONTAP. However, you can use the API to avail this functionality.

=== Minimum version support for Flash Cache in Azure
The minimum Cloud Volumes ONTAP version required for configuring Flash Cache in Azure is 9.13.1 GA. You can only use ONTAP 9.13.1 GA and later versions for deploying Flash Cache on Cloud Volumes ONTAP systems in Azure. 

For supported configurations, see https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#single-node-systems[Supported configurations in Azure^].

=== Free trials for marketplace subscriptions deprecated
The 30-day automatic free trial or evaluation license for pay-as-you-go subscriptions in cloud provider's marketplace will no longer be available in Cloud Volumes ONTAP. The charging for any type of marketplace subscription (PAYGO or annual contract) will be activated from the first use, without any free trial period.


== 10 June 2024

=== Cloud Volumes ONTAP 9.15.0
BlueXP can now deploy and manage the Cloud Volumes ONTAP 9.15.0 in AWS, Azure, and Google Cloud.

https://docs.netapp.com/us-en/cloud-volumes-ontap-9150-relnotes/[Learn about the new features included in this release of Cloud Volumes ONTAP^].


== Older release notes

We retain a year of release notes for Cloud Volumes ONTAP in the Console. The older notes are archived.


