=== Cloud Volumes ONTAP integration with Microsoft OneLake

Cloud Volumes ONTAP now supports integration with https://learn.microsoft.com/en-us/fabric/onelake/onelake-overview[Microsoft OneLake^] in public preview. You can integrate Cloud Volumes ONTAP with Microsoft Fabric OneLake, enabling existing Cloud Volumes ONTAP NAS data to be used by Microsoft analytics and AI services such as Power BI, Azure AI Search, OpenAI, and Microsoft Copilot, without moving or duplicating the data. The integration uses ONTAP S3 multi-protocol access to connect Cloud Volumes ONTAP to an existing OneLake lakehouse through an Azure on-premises data gateway.

.Related articles and resources:

* https://www.netapp.com/blog/optimize-ai-analytics-microsoft-onelake/?utm_content=nativelink&utm_medium=internal&utm_source=linkedin&utm_campaign=b2d-port-all-na-ww-digi-blog-1747859361262&es_id=956c739202[NetApp blog: Optimize AI and analytics with Microsoft OneLake and NetApp Cloud Volumes ONTAP^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-azure-onelake.html[Integrate Cloud Volumes ONTAP systems with Microsoft OneLake for AI and Analytics^]
* https://www.netapp.com/media/160786-na-1263-netapp-cloud-volumes-ontap-azure-onelake.pdf[Cloud Volumes ONTAP integration with Microsoft OneLake - Technical brief^]

