=== Cloud Volumes ONTAP support for next generation Google Cloud VMs

With 9.19.1, NetApp transitions Cloud Volumes ONTAP high -availability (HA) deployments off N2 VMs to the next generation Google Cloud C3-series VMs for a faster and more scalable experience.

[NOTE]
Cloud Volumes ONTAP HA configuration supports the C3 series only in single availability zone (AZ) deployments.

You can now take advantage of C3-series VMs while deploying Cloud Volumes ONTAP 9.19.1 and later in Google Cloud. The C3 series machines offer improved performance and higher capacity limits by using Google Virtual NIC (gVNIC) and Hyperdisk Balanced disks that ensure dynamic performance for intensive workloads. 

If your Cloud Volumes ONTAP system runs 9.19.1 or later, the preconfigured packages that you use for easy single node deployments automatically use C3 VMs, while enabling you to customize the IOPS and throughput parameters based on your workload needs. Similarly, while creating aggregates, you can add Hyperdisk Balanced disks to achieve better performance and scalability in Google Cloud. Additionally, you can select the LSSD variants of the C3 series machines for default Flash Cache support.

You can't change C3 VMs to N2 series VMs and vice versa. for  when adding volumes to aggregates because C3 supports only Hyperdisk Balanced disks. Similarly, when replicating a system with N2 VM types to a C3 VM, the disk type is set by default to Hyperdisk Balanced.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html[Supported configurations for Cloud Volumes ONTAP in Google Cloud^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series[Google documents: C3 machine series^]

=== Simplified Cloud Volumes ONTAP deployment in Google Cloud
 
You can now use Quick create to deploy Cloud Volumes ONTAP in Google Cloud for both single-node and high-availability (HA) configurations. This streamlined process reduces the number of steps compared to the advanced method, automatically sets default values on a single page, and minimizes navigation, making deployment faster and easier.

.Related links

* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-gcp.html[Deploy Cloud Volumes ONTAP in Google Cloud with Quick create^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-gcp.html[Deploy Cloud Volumes ONTAP using advanced options in Google Cloud^]

=== Introducing access roles for Cloud Volumes ONTAP

NetApp is introducing identity and access management (IAM) roles for Cloud Volumes ONTAP, enabling role-based access control (RBAC) for enhanced security and streamlined compliance. You can continue to log in to the NetApp Console using your existing credentials. However, authentication will now be routed through identity federation, enabling the Console administrator to have more granular control over Cloud Volumes ONTAP user operations. The following roles are now available:

* *Cloud Volumes ONTAP Viewer*: Grants read-only access to Cloud Volumes ONTAP screens and tabs. Certain screens and action buttons are disabled in this role.

* *Cloud Volumes ONTAP Operator*: Enables day-to-day management tasks, including adding volumes, configuring replication, and managing storage.

* *Cloud Volumes ONTAP Administrator*: Provides full access to all Cloud Volumes ONTAP operations.

[NOTE]
These roles are currently available in preview mode. In a future release, when the Console administrator is granted permissions for Cloud Volumes ONTAP user management and role assignment, these roles will be activated.

The Console admin assigns roles to Cloud Volumes ONTAP users based on their organization from *Administration > Identity*, and the role permissions apply across all Cloud Volumes ONTAP systems within that organization.

Cloud Volumes ONTAP roles apply to Amazon Web Service (AWS), Microsoft Azure (Azure), and Google Cloud environments.

.Related links

* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[NetApp Console access roles^]
* https://docs.netapp.com/us-en/console-setup-admin/reference-iam-cvo-roles.html[Cloud Volumes ONTAP access roles in NetApp Console^]

== Well-architected configuration analysis for Cloud Volumes ONTAP in Azure

The NetApp Console now supports well-architected configuration analysis for Cloud Volumes ONTAP systems running in Microsoft Azure. The Console analyzes your deployments daily and provides a well-architected status, insights, and recommendations to help you maintain systems that align with NetApp best practices and the well-architected framework.

The well-architected dashboard displays the total number of analyzed systems and categorizes their resources by configuration and severity level.
If you are a system administrator, you can view recommendations for any configuration issue within your organization directly from the Console dashboard and download a CSV report of all the recommendations.
Configurations are categorized according to:

*	*Reliability*: Ensures workloads operate correctly and consistently, even in the event of disruptions.
*	*Security*: Safeguards data, systems, and assets through risk assessments and mitigation.
*	*Operational excellence*: Optimizes architecture to maximize business value.
*	*Cost optimization*: Reduces and optimizes costs for greater business value.

.Related links

* https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html[Configuration analysis for Cloud Volumes ONTAP^]
* https://docs.netapp.com/us-en/console-well-architected/improve-configurations-cvo.html[Implement well-architected system configurations^]

