=== Support for Google Cloud Infrastructure Manager

Cloud Volumes ONTAP now uses https://docs.cloud.google.com/infrastructure-manager/docs/overview[Google Cloud Infrastructure Manager] (IM) instead of https://docs.cloud.google.com/deployment-manager/docs/deprecations[Cloud Deployment Manager] for all new deployments in Google Cloud. This change has been made because Google will deprecate Google Cloud Deployment Manager in the near future. 

For your existing deployments in Google Cloud, you need to upgrade your systems to Cloud Volumes ONTAP 9.16.1 or later, and then manually run a transition tool for migrating from Google Cloud Deployment Manager to Cloud Infrastructure Manager. This is a one-time process, after which your system will automatically start using Cloud Infrastructure Manager. Refer to 

For the converted systems and new deployments, note these points:

* 

* Tools link
* https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#console-agent-4-2-0[NetApp Console Agent 4.2.0 Release Notes] 
* https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log[Permissions required for Google Cloud Infrastructure Manager^]


