=== Support for private-mode deployments with capacity-based licenses

Now you can deploy Cloud Volumes ONTAP systems in private mode with capacity-based licenses for all hyperscalers, Amazon Web Services (AWS), Microsoft Azure (Azure), and Google Cloud. This capability enables you to deploy Cloud Volumes ONTAP systems in private mode without a need to purchase a capacity-based bring your own license or BYOL package upfront from NetApp. When you deploy a system in private mode, NetApp provides 500 GiB of usable capacity at no charge. After you exceed 500 GiB, you are required to purchase a capacity-based _Essentials_ package from NetApp and assign it to your Cloud Volumes ONTAP systems. You can continue to purchase additional Essentials packages to increase the amount of usable capacity as your workload requirement grows.

NetApp recommends capacity-based licensing for all private-mode Cloud Volumes ONTAP deployments. You can already convert existing private-mode deployments from node-based licenses to capacity-based licensing by purchasing an Essentials (bring your own license or BYOL) package directly from NetApp. This new deployment capability, combined with the conversion option, advances NetApp's phased plan to move away from node-based licensing in favor of capacity-based licensing. Unlike node-based licensing, which allocates a fixed capacity to each system, capacity-based licensing draws from a shared capacity pool across your Cloud Volumes ONTAP systems, giving you greater flexibility to redistribute workloads as your storage needs change.

.Related links

* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-license-management.html[Learn about Cloud Volumes ONTAP BYOL^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses[End of availability of node-based licenses^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html[Manage node-based licenses for Cloud Volumes ONTAP^]



