=== Support for private-mode deployments with capacity-based licenses

You can now deploy Cloud Volumes ONTAP systems in private mode with capacity-based licenses in Amazon Web Services (AWS), Microsoft Azure (Azure), and Google Cloud. In private mode, you have two deployment options: purchase a capacity-based _Essentials_ package from NetApp (bring your own license or BYOL) and assign it to your system, or deploy without a license. 

When you deploy without a license, NetApp provides 500 GiB of usable capacity at no charge. After you exceed 500 GiB, you need to purchase an Essentials package from NetApp and assign it to your Cloud Volumes ONTAP system. As your workload requirements grow, you can purchase additional Essentials packages to increase your usable capacity.

NetApp recommends capacity-based licensing for all private-mode Cloud Volumes ONTAP deployments. If you have existing private-mode deployments with node-based licenses, you can convert them to capacity-based licensing by purchasing an Essentials package from NetApp. This new deployment capability, combined with the conversion option, supports NetApp's plan to move away from node-based licensing to capacity-based licensing.

.Related links

* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-license-management.html[Learn about Cloud Volumes ONTAP BYOL^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses[End of availability of node-based licenses^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html[Manage node-based licenses for Cloud Volumes ONTAP^]



