=== Improved Cloud Volumes ONTAP support with Google Cloud C3 VMs
 
Cloud Volumes ONTAP now has enhanced support for the Google Cloud C3 series VMs, enabling these additional capabilities:
 
* Within your Cloud Volumes ONTAP deployments, you can switch VM types among different variants within the C3 family.
* While switching, the Google network service egress network tier (Tier-1) will apply automatically if c3-standard-44 or c3-standard-88 is selected as the target VM. And if you switch to any other variant, the egress network tier will be set to Standard.
* If you select the local SSD (LSSD) variants of the C3 VMs, Flash Cache gets enabled by default. You can't switch between C3 LSSD VM variants in your Cloud Volumes ONTAP deployment, even if the target variant supports Flash Cache.
* You can also add volumes to both new and existing aggregates on these VMs.

.Related links
* https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html[Supported configurations for Cloud Volumes ONTAP in Google Cloud^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#cloud-volumes-ontap-support-for-next-generation-google-cloud-vms[Cloud Volumes ONTAP support for next generation Google Cloud VMs^]