=== Simplified Cloud Volumes ONTAP deployment in Azure
 
You can now use Quick create to deploy Cloud Volumes ONTAP in Azure for both single-node and high-availability (HA) configurations. This streamlined process reduces the number of steps compared to the advanced method, automatically sets default values on a single page, and minimizes navigation, making deployment faster and easier.

[NOTE]
If you use Quick create to deploy a new Cloud Volumes ONTAP system in Azure, the Console selects the Azure credentials by default. You can deploy all of your Cloud Volumes ONTAP systems using the initial Azure credentials. If you want to use another subscription and/or credentials, you need to switch to the advanced-mode deployment. This limitation will be addressed in a future release.


.Related links

* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html[Deploy Cloud Volumes ONTAP in Azure with Quick create^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html[Deploy Cloud Volumes ONTAP using advanced options in Azure^]