=== Introducing simplified onboarding of Cloud Volumes ONTAP from AWS Marketplace

NetApp introduces a simplified onboarding flow for Cloud Volumes ONTAP from AWS Marketplace to eliminate friction, reduce manual steps, and ensure a smoother onboarding experience.

Deploying Cloud Volumes ONTAP from AWS Marketplace required switching between the AWS Console and the NetApp Console and manually configuring roles, policies, and credentials, making the onboarding process slow and error-prone. The onboarding flow now begins with subscribing to the standalone Cloud Volumes ONTAP listing or a multi-subscription listing (combining Cloud Volumes ONTAP capacity and NetApp data services) on the AWS Console, enabling https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#flexible-billing-for-cloud-volumes-ontap-and-data-services-in-aws[flexible billing for Cloud Volumes ONTAP and data services in AWS^]. The Console then continues to guide you through automatic subscription association, reducing manual configuration and navigation steps. The workflow also reduces manual configuration of the Console agent by automatically creating and assigning the required IAM roles and policies, then storing them during the agent deployment. 

After completing the Console agent configuration, you can navigate directly to the `Quick create` wizard for a faster, simplified Cloud Volumes ONTAP deployment, making your transition from a marketplace subscription to a fully operational Cloud Volumes ONTAP environment more efficient.


.Related links

* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-aws.html[Deploy Cloud Volumes ONTAP with Quick create^]






