=== Cloud Volumes ONTAP support for next generation Google Cloud VMs

You can now use the next generation Google Cloud C3 series VMs when deploying or upgrading Cloud Volumes ONTAP 9.18.1 and later in Google Cloud. The C3 series machines offer improved performance and higher capacity limits by using Google Virtual NIC (gVNIC) and Hyperdisk Balanced disks that ensure dynamic performance for intensive workloads.

[NOTE]
For now, Cloud Volumes ONTAP supports the C3 series only for single-node deployments in Google Cloud.

We offer preconfigured packages for easy Cloud Volumes ONTAP deployments, while enabling you to customize the IOPS and throughput parameters based on your workload needs. You can also add Hyperdisk Balanced disks to your aggregates to achieve better performance and scalability in Google Cloud. Additionally, you can select the LSSD variants of the C3 series machines for default Flash Cache support.

You can't change the disk type for C3 VMs when adding volumes to aggregates because C3 supports only Hyperdisk Balanced disks. Similarly, when replicating a system with N2 VM types to a C3 VM, the disk type is set by default to Hyperdisk Balanced.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html[Supported configurations for Cloud Volumes ONTAP in Google Cloud^]

https://docs.cloud.google.com/compute/docs/general-purpose-machines#c3_series[Google documents: C3 machine series^]

 
